In [ ]:
# Assignment 1 - Activation Functions with Graphs

import numpy as np
import matplotlib.pyplot as plt

# Input values
x = np.linspace(-10, 10, 100)

# Sigmoid Function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Tanh Function
def tanh(x):
    return np.tanh(x)

# ReLU Function
def relu(x):
    return np.maximum(0, x)

# Plot Sigmoid
plt.figure(figsize=(6,4))
plt.plot(x, sigmoid(x))
plt.title("Sigmoid Function")
plt.xlabel("x")
plt.ylabel("sigmoid(x)")
plt.grid()
plt.show()

# Plot Tanh
plt.figure(figsize=(6,4))
plt.plot(x, tanh(x))
plt.title("Tanh Function")
plt.xlabel("x")
plt.ylabel("tanh(x)")
plt.grid()
plt.show()

# Plot ReLU
plt.figure(figsize=(6,4))
plt.plot(x, relu(x))
plt.title("ReLU Function")
plt.xlabel("x")
plt.ylabel("relu(x)")
plt.grid()
plt.show()

Input Values: [-2 -1  0  1  2]

Sigmoid Function:
[0.11920292 0.26894142 0.5        0.73105858 0.88079708]

Tanh Function:
[-0.96402758 -0.76159416  0.          0.76159416  0.96402758]

ReLU Function:
[0 0 0 1 2]


pip install numpy matplotlib